// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mahviqoiqppiwepcrmpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1haHZpcW9pcXBwaXdlcGNybXByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTkwNjksImV4cCI6MjA3MTQzNTA2OX0.BRyZR8jOz6FSTascC6hKjq7_l7KahdCr4VPTE6KQnMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});